export const BOTSWANA_LOCATIONS = [
  "Artesia",
  "Bobonong",
  "Bokaa",
  "Bokspits",
  "Bontleng, Gaborone",
  "Borolong",
  "Boteti",
  "Botlhapatlou",
  "Broadhurst, Gaborone",
  "Charles Hill",
  "Chobe",
  "D'Kar",
  "Dibete",
  "Digawana",
  "Dikgatlhong",
  "Ditshegwane",
  "Dukwi",
  "Etsha",
  "Francistown",
  "Gabane",
  "Gaborone",
  "Gaborone North",
  "Gaborone West",
  "Gakuto",
  "Gamodubu",
  "Ghanzi",
  "Goodhope",
  "Gumare",
  "Gweta",
  "Hukuntsi",
  "Jwaneng",
  "Kachikau",
  "Kang",
  "Kanye",
  "Kareng",
  "Kasane",
  "Kazungula",
  "Kgatleng",
  "Khakhea",
  "Khudumelapye",
  "Kopong",
  "Kumakwane",
  "Kweneng",
  "Lentsweletau",
  "Lerala",
  "Letlhakane",
  "Letlhakeng",
  "Lesoma",
  "Lobatse",
  "Lotlhakane",
  "Mabule",
  "Mahalapye",
  "Maitengwe",
  "Makaleng",
  "Makalamabedi",
  "Makobo",
  "Malolwane",
  "Mankgodi",
  "Manyana",
  "Marapong",
  "Masunga",
  "Matebeleng",
  "Mathangwane",
  "Mathubudukwane",
  "Matsiloje",
  "Maun",
  "Maunatlala",
  "Metsimotlhabe",
  "Mmadinare",
  "Mmankgodi",
  "Mmopane",
  "Mmathethe",
  "Mochudi",
  "Mokolodi",
  "Mogoditshane",
  "Mogobane",
  "Molepolole",
  "Molapowabojang",
  "Molopo",
  "Mookane",
  "Moshaweng",
  "Moshupa",
  "Mosopa",
  "Nata",
  "Ncojane",
  "Nokaneng",
  "Nshakashogwe",
  "Nkange",
  "Oodi",
  "Orapa",
  "Otse",
  "Palapye",
  "Pandamatenga",
  "Phakalane, Gaborone",
  "Pilane",
  "Pitsane",
  "Radisele",
  "Ramotswa",
  "Ramatlabama",
  "Ramonaka",
  "Rasesa",
  "Ratholo",
  "Rakops",
  "Salajwe",
  "Sebina",
  "Sefhare",
  "Sefophe",
  "Sehithwa",
  "Selebi-Phikwe",
  "Seronga",
  "Serowe",
  "Shashe Mooke",
  "Shakawe",
  "Shoshong",
  "Sikwane",
  "Sua Pan",
  "Takatokwane",
  "Tamasane",
  "Tati Siding",
  "Thamaga",
  "Tlokweng",
  "Tlokweng, Gaborone",
  "Tonota",
  "Toteng",
  "Tsabong",
  "Tsau",
  "Tswapong",
  "Tutume",
  "Werda",
  "Westwood, Gaborone",
].sort((a, b) => a.localeCompare(b));
